spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/user_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Turkey
    #username: root
    #password: MyPassword
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
    data:
      redis:
        host: 127.0.0.1
        port: 6379
        lettuce:
          pool:
            max-active: 10
            max-idle: 10
            min-idle: 2
  redis:
    port: 6379
    host: 127.0.0.1

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p}
      %m%n'
server:
  port: 8089
springdoc:
  packagesToScan: com.i2it.auth
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

management:
  tracing:
    sampling:
      probability: 1.0
