  server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: patient-service
        uri: lb://patient-service
        predicates:
          - Path=/patient/**
        filters:
          - AuthenticationFilter
          #- RewritePath=/authentication/(?<path>.*), /$\{path}
      - id: authentication-service
        uri: lb://authentication-service
        predicates:
          - Path=/authentication/**
        filters:
          - AuthenticationFilter
          #- RewritePath=/authentication/(?<path>.*), /$\{path}
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
          - Path=/v3/api-docs/**
        filters:
          - AuthenticationFilter
          #- RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

springdoc:
  swagger-ui:
    urls:
      - name: authentication
        url: /v3/api-docs/authentication
    path: /swagger-ui.html

management:
  tracing:
    sampling:
      probability: 1.0